version: "3.8"

services:
  web:
    build: ./project #->Donde está el Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMETN=dev
      - TESTING=0